# Generated by Django 5.1.4 on 2024-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authors_options_alter_authors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='image',
            field=models.ImageField(upload_to='author_images/'),
        ),
    ]
