# Generated by Django 5.1.4 on 2024-12-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
